import Link from "next/link";
import { connection } from "next/server";
import { notFound } from "next/navigation";
import { sqlite } from "@/lib/db";
import { findMatches, getImport } from "@/lib/resume-import/storage";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AddFactForm, DeleteForm, ProposalEditor, RetryForm } from "../review-forms";
export const metadata = { title: "Review imported resume · Headhunter" };
export default async function ImportReviewPage({ params }: PageProps<"/career-profile/import/[id]">) {
  await connection(); const { id } = await params; const record = getImport(sqlite, id); if (!record) notFound();
  const experiences = sqlite.prepare("SELECT id,title || ' · ' || company as label FROM career_experiences WHERE verification_state NOT IN ('archived','prohibited') ORDER BY start_date DESC").all() as { id: string; label: string }[];
  const pending = record.proposals.filter(p => p.state === "pending");
  const reviewed = record.proposals.filter(p => p.state !== "pending");
  return <div className="mx-auto w-full max-w-6xl px-5 py-8 sm:px-8 sm:py-12 lg:px-12">
    <Button asChild variant="ghost" className="mb-5 -ml-3"><Link href="/career-profile/import">← Resume imports</Link></Button>
    <header className="mb-8 flex flex-wrap items-end justify-between gap-5 border-b pb-7"><div className="min-w-0"><h1 className="break-words text-3xl font-semibold tracking-tight">Review {record.name}</h1><p className="mt-3 text-sm text-muted-foreground">{pending.length} facts to review · {reviewed.length} decided</p></div><Button asChild variant="outline"><Link href="/career-profile">Open evidence bank</Link></Button></header>
    {record.warning ? <p role="alert" className="mb-6 rounded-lg border border-amber-600/30 bg-amber-600/5 p-4 text-sm leading-6">{record.warning}</p> : null}
    <div className="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-4"><p className="text-sm leading-6 text-muted-foreground">These are local extraction proposals, not verified facts. Compare each with the source, correct it, then approve or reject. Blank fields mean the source did not establish a value. Save drafts before leaving this page.</p>
      {!pending.length ? <div className="rounded-lg border border-dashed p-6"><h2 className="font-semibold">{record.proposals.length ? "All proposals reviewed" : "No structured facts found"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{record.proposals.length ? "Approved facts are available to your resume studio. Rejected proposals stay rejected." : "The source is preserved. Add a proposal from an excerpt, or paste a clearer copy with section headings."}</p>{record.proposals.some(p=>p.state==="approved") ? <Button asChild variant="outline" className="mt-4"><Link href="/resumes">Continue to resume studio</Link></Button> : null}</div> : null}
      {pending.map((p,index) => <details key={p.id} id={`proposal-${p.id}`} open={index === 0} className="rounded-lg border bg-card"><summary className="cursor-pointer px-5 py-4 outline-none focus-visible:ring-2 focus-visible:ring-ring"><span className="block break-words font-medium"><span className="capitalize">{p.kind}</span> · {p.fields.title || p.fields.name || p.fields.action || "Complete this fact"}</span></summary><div className="space-y-5 border-t p-5"><div className="rounded-md bg-muted/50 p-4"><h3 className="text-sm font-medium">From your source</h3><blockquote className="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{p.sourceQuote}</blockquote></div><ProposalEditor proposal={p} experiences={experiences} matches={findMatches(sqlite,p.kind,p.fields)}/></div></details>)}
      {reviewed.length ? <section className="space-y-3 pt-5" aria-labelledby="reviewed-heading"><h2 id="reviewed-heading" className="font-semibold">Reviewed facts</h2>{reviewed.map(p => <div key={p.id} className="flex items-start justify-between gap-3 rounded-md border p-4"><div className="min-w-0"><p className="break-words text-sm font-medium">{p.fields.title || p.fields.name || p.fields.action || p.kind}</p>{p.evidenceId ? <Link href={`/sources/evidence/${p.evidenceId}`} className="mt-1 block text-xs underline underline-offset-4">View saved fact</Link> : null}</div><Badge variant={p.state === "approved" ? "signal" : "outline"}>{p.state}</Badge></div>)}</section> : null}
    </div><aside className="min-w-0 space-y-5"><details className="rounded-lg border bg-card" open><summary className="cursor-pointer p-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-ring">Recovered source</summary><div className="border-t p-4"><p className="mb-3 text-xs leading-5 text-muted-foreground">Text is retained as read from the file. Page layout, images, and reading order may differ from the original.</p><pre className="max-h-[32rem] overflow-y-auto whitespace-pre-wrap break-words font-sans text-xs leading-6" tabIndex={0} aria-label="Recovered resume text">{record.source_text}</pre></div></details><details className="rounded-lg border bg-card"><summary className="cursor-pointer p-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-ring">Add a missed fact</summary><div className="border-t p-4"><AddFactForm id={id}/></div></details><div className="rounded-lg border bg-card p-4"><p className="mb-3 text-xs leading-5 text-muted-foreground">Retry reads the saved text. It keeps all edits and decisions and adds only missing proposals.</p><RetryForm id={id}/></div><details className="rounded-lg border"><summary className="cursor-pointer p-4 text-sm text-muted-foreground">Remove saved import</summary><div className="border-t p-4"><DeleteForm id={id}/></div></details></aside></div>
  </div>;
}
