import Link from "next/link";
import { connection } from "next/server";
import { db } from "@/lib/db";
import { jobs, applicationEvents, applicationSubmissions, pipelineStages } from "@/lib/db/schema";
import { calculateFunnel } from "@/lib/analytics/funnel";
import { Button } from "@/components/ui/button";

export default async function AnalyticsPage({ searchParams }: { searchParams: Promise<{ window?: string }> }) {
  await connection();
  const query = await searchParams;
  const days = query.window === "all" ? null : query.window === "90" ? 90 : 30;
  const [applications, events, submissions, stages] = await Promise.all([
    db.select({ id: jobs.id, title: jobs.title, company: jobs.company }).from(jobs),
    db.select({ jobId: applicationEvents.jobId, kind: applicationEvents.kind, toStage: applicationEvents.toStage, occurredAt: applicationEvents.occurredAt }).from(applicationEvents),
    db.select({ jobId: applicationSubmissions.jobId, submittedAt: applicationSubmissions.submittedAt }).from(applicationSubmissions),
    db.select({ key: pipelineStages.key, category: pipelineStages.category }).from(pipelineStages),
  ]);
  const funnel = calculateFunnel({ applications, events, submissions, stages }, new Date(), days);
  return <div className="mx-auto w-full max-w-5xl px-5 py-8 sm:px-8 sm:py-12"><header className="border-b pb-8"><h1 className="text-3xl font-semibold tracking-tight">Application funnel</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">See what happened after applying, with every number tied to its recorded applications.</p></header><nav aria-label="Funnel time window" className="my-6 flex gap-2">{["30", "90", "all"].map((value) => <Button key={value} asChild variant={String(days ?? "all") === value ? "default" : "outline"}><Link href={`/analytics?window=${value}`}>{value === "all" ? "All time" : `Last ${value} days`}</Link></Button>)}</nav><section className="rounded-lg border bg-card p-5 sm:p-7"><h2 className="text-xl font-semibold">{funnel.sampleSize} recorded applications</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Cohort: first recorded Applied event or submission {funnel.since ? `from ${funnel.since.toISOString().slice(0, 10)}` : "from all recorded history"} through {funnel.until.toISOString().slice(0, 10)} UTC. Outcomes are observed through now. Explicit Applied waivers are included.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Each percentage is the share of this cohort that reached the named milestone after applying. Repeated transitions count once; skipped stages are not inferred.</p><div className="mt-6 divide-y">{funnel.rows.map((row) => <details key={row.category} className="py-4"><summary className="cursor-pointer"><span className="ml-1 text-sm font-medium">{row.label}</span><span className="float-right font-mono text-sm">{row.count}/{row.denominator} · {row.rate === null ? "—" : `${(row.rate * 100).toFixed(1)}%`}</span></summary>{row.applications.length ? <ul className="mt-4 space-y-2">{row.applications.map((application) => <li key={application.id}><Link className="text-sm text-primary" href={`/jobs/${application.id}#application-workspace-heading`}>{application.company} · {application.title}</Link></li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">No recorded applications at this milestone.</p>}</details>)}</div></section><p className="mt-5 text-sm leading-6 text-muted-foreground">{funnel.sampleSize < 20 ? "Small sample: use these counts to check your workflow, not to draw conclusions about strategy. " : "These are descriptive counts, not evidence that one strategy causes better results. "}Recent applications have had less time to progress; pending outcomes are included in the denominator. Recruiter screens and interview rounds are reported separately, without claiming either is a qualified interview.</p>{funnel.missingAppliedHistory ? <p className="mt-3 text-sm text-muted-foreground">{funnel.missingAppliedHistory} opportunities have later-stage events but no recorded application date; they are excluded from this cohort. <Link href="/pipeline?view=timeline" className="text-primary">Review pipeline history</Link>.</p> : null}</div>;
}
